name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  collect-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: '${{ steps.changed-files.outputs.all_changed_files }}'
      image_changed: '${{ steps.changed-files.outputs.any_changed }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          files: |
            **/.metadata.json
            **/Dockerfile
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          json: true
          escape_json: false

  lint:
    runs-on: ubuntu-latest
    needs: collect-images
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.collect-images.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate metadata
        working-directory: "${{ matrix.image }}"
        # language=Bash
        run: |
          test -f .metadata.json
          jq -cerM 'if (.version | length) > 0 then .version else error("empty version") end' .metadata.json
          jq -cerM 'if (.description | length) > 0 then .description else error("empty description") end' .metadata.json
          jq -cerM 'if (.platforms | length) > 0 then .platforms else error("empty platforms") end' .metadata.json
          jq -cerM 'if (.imageName | length) > 0 then .imageName else error("empty imageName") end' .metadata.json
          jq -cerM 'if (.tagFormats | length) > 0 then .tagFormats else error("empty tagFormats") end' .metadata.json

  build:
    runs-on: ubuntu-latest
    needs: collect-images
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJSON(needs.collect-images.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Read metadata
        id: metadata
        working-directory: "${{ matrix.image }}"
        # language=Bash
        run: |
          echo "version=$(jq -cerM '.version' .metadata.json)" >> $GITHUB_OUTPUT
          echo "platforms=$(jq -cerM '.platforms | join(",")' .metadata.json)" >> $GITHUB_OUTPUT
          echo "qemu=$(jq -crM '.qemu // false' .metadata.json)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        if: steps.metadata.outputs.qemu == 'true'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ steps.metadata.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:${{ matrix.image }}'
          platforms: ${{ steps.metadata.outputs.platforms }}
          build-args: |
            VERSION=${{ steps.metadata.outputs.version }}

  build-result:
    if: always()
    needs:
      - collect-images
      - build
      - lint
    runs-on: ubuntu-latest
    steps:
      - if: needs.collect-images.outputs.image_changed != 'true' && needs.build.result != 'success' && needs.build.result != 'skipped'
        # language=Bash
        run: echo '${{ needs.build.result }}' && exit 1
