name: Release

on:
  create:

  workflow_dispatch:
    inputs:
      image:
        type: string
        required: true
        description: Directory name to release
      latest:
        type: boolean
        required: false
        description: whether tagging latest to the image or not

env:
  REGISTRY: "ghcr.io"
  OWNER: "${{ github.repository_owner }}"


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'create' && github.event.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v3

      - name: Read tag
        id: metadata
        # language=Bash
        run: |
          if [ '${{ github.event_name }}' == 'workflow_dispatch' ]; then
            image='${{ inputs.image }}'
            echo 'use_latest=${{ inputs.latest }}' >> $GITHUB_OUTPUT
          else
            tag='${{ github.event.ref }}'
            image="${tag%%@*}"
            echo 'use_latest=true' >> $GITHUB_OUTPUT
          fi
          echo "image=$image" >> $GITHUB_OUTPUT
          echo "version=$(jq -cerM '.version' "$image/.metadata.json")" >> $GITHUB_OUTPUT
          echo "description=$(jq -cerM '.description' "$image/.metadata.json")" >> $GITHUB_OUTPUT
          echo "platforms=$(jq -cerM '.platforms | join(",")' "$image/.metadata.json")" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=${{ steps.metadata.use_latest }}
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ steps.metadata.outputs.image }}
          tags: |
            type=raw,value=${{ steps.metadata.outputs.version }}
          labels: |
            org.opencontainers.image.title=${{ steps.metadata.outputs.image }}
            org.opencontainers.image.url='${{ github.event.repository.html_url }}/tree/HEAD/${{ steps.metadata.outputs.image }}'
            org.opencontainers.image.source='${{ github.event.repository.html_url }}/tree/HEAD/${{ steps.metadata.outputs.image }}'
            org.opencontainers.image.description='${{ steps.metadata.outputs.description }}'
            org.opencontainers.image.base.name=scratch

#            org.opencontainers.image.documentation=URL

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Load buildkit state
        uses: isac322/buildkit-state@v1
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:${{ steps.metadata.outputs.image }}'
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ steps.metadata.outputs.platforms }}
          build-args: |
            VERSION=${{ steps.metadata.outputs.version }}

      - name: Export binaries to local
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}:${{ steps.metadata.outputs.image }}'
          platforms: ${{ steps.metadata.outputs.platforms }}
          build-args: |
            VERSION=${{ steps.metadata.outputs.version }}
          outputs: type=local,dest=bin
          target: output

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{ steps.metadata.outputs.image }}@${{ steps.metadata.outputs.version }}'
          files: |
            bin/*
          generate_release_notes: true
