name: Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/.version
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          json: true
      - name: Create tag
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v6
        with:
          # language=JavaScript
          script: |
            import { readFile } from 'node:fs/promises'
            import path from 'node:path'
            const images = JSON.parse("${{ steps.changed-files.outputs.all_changed_files }}")
            console.log(`Will tag ${images}`)
            
            await Promise.all(images.map(image => async () => {
                const version = await readFile(path.join(image, '.version'))
                await github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: `refs/tags/${image}@${version}`,
                    sha: context.sha
                })
            }))
