name: Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  collect-bumped:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **/.version
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 1
          json: true

  tag:
    runs-on: ubuntu-latest
    if: needs.collect-images.outputs.matrix != ""
    needs: collect-bumped
    strategy:
      matrix:
        image: ${{ fromJSON(needs.collect-images.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Read version
        id: version
        working-directory: "${{ matrix.image }}"
        # language=Bash
        run: echo "version=$(cat .version)" >> $GITHUB_OUTPUT
      - name: Create tag
        uses: actions/github-script@v5
        with:
          # langauge=JavaScript
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ matrix.image }}@${{ steps.version.outputs.version }}',
              sha: context.sha
            })
